# Tarefa: prazo, nome, status, ...
# Lista: cria/ acessa o lugar onde guarda as tarefa, SABE adicionar, marcar, remover as tarefas e tal, ...
# Usuario: nome, PODE adicionar, marcar, remover suas tarefa tlgd, ??????codigo de acesso talvez??????#